package com.swapit.domain.enums;

public enum SwapRequestStatus {
    CREATED,
    PHOTO_UPLOADED,
    INSPECTION_COMPLETED,
    PRE_VALUATION_READY,
    PRE_VALUATION_ACCEPTED,
    BOOKING_CONFIRMED,
    INSTANT_CALL_REQUESTED,
    CREW_ASSIGNED,
    PICKUP_IN_PROGRESS,
    CREW_ARRIVED,
    PICKUP_COMPLETED,
    FINAL_INSPECTION_IN_PROGRESS,
    FINAL_VALUATION_READY,
    RE_REVIEW_REQUESTED,
    RE_REVIEW_COMPLETED,
    CREDIT_ISSUED,
    COMPLETED,
    CANCELLED
}
